---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-prepare
  namespace: inference
  labels:
    name: video-prepare
spec:
  replicas: 1
  selector:
    matchLabels:
      name: video-prepare
  template:
    metadata:
      namespace: inference
      labels:
        name: video-prepare
    spec:
      nodeSelector:
        gpu-type: RTX
      restartPolicy: Always
      containers:
        - name: video-prepare
          image: wildflowerschools/wf-deep-docker:video-prepare-v1
          volumeMounts:
          - name: data
            mountPath: /data
          envFrom:
            - secretRef:
                name: gpu-client-secrets
          env:
            - name: RABBIT_HOST
              value: rabbitmq-video-queue.inference.svc.cluster.local
            - name: VIDEO_QUEUE_NAME
              value: video-processing-queue
            - name: POSE_QUEUE_NAME
              value: pose-processing-queue
            - name: LOG_LEVEL
              value: INFO
      volumes:
        - name: data
          hostPath:
            path: /data
            type: Directory
