---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-video-queue
  namespace: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-video-queue
  template:
    metadata:
      namespace: inference
      labels:
        app: rabbitmq-video-queue
    spec:
      nodeSelector:
        gpu-type: RTX
      containers:
        - name: rabbitmq-video-queue
          image: rabbitmq:3.7-management-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672


---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-video-queue
  namespace: inference
  labels:
    app: rabbitmq-video-queue
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    name: queue
    targetPort: 5672
  - port: 15672
    name: mgmt
    targetPort: 15672
  selector:
    app: rabbitmq-video-queue
